#!/usr/bin/env python3
"""Recompute Bayesian posterior rewards using a learned unified analyzer.

This script reads an existing bayesian_reward_debug.jsonl file generated by
Bayesian Full GRPO, then uses a learned unified analyzer LoRA adapter to
re-judge:

1. prior_judge:
   problem + candidate strategies -> suitability JSON

2. evidence_judge:
   problem + strategy + reasoning + final answer + correctness -> evidence JSON

The prompt bodies are matched to prepare_analyzer_training_data.py.
By default, the same task prefix style used for unified multi-task SFT is
prepended. Use --no_task_prefix to disable that prefix.

Outputs:
- learned_posterior_debug.jsonl
- group_metrics.jsonl
- summary.json
"""

from __future__ import annotations

import argparse
import json
import math
import re
import statistics
from collections import defaultdict
from pathlib import Path
from typing import Any, Optional


JUDGE_JSON_SYSTEM_PROMPT = """You are a JSON-only evaluation API.
Return exactly one valid JSON object and nothing else.
Do not include markdown.
Do not include ```json.
Do not include explanations before or after the JSON.
Use double quotes for all keys and string values.
Do not use LaTeX notation inside JSON string values.
Do not use backslashes inside JSON string values.
Write all reason/key fields in plain English text only.
The first character of your response must be {.
The last character of your response must be }."""


TASK_PREFIXES = {
    "evidence_judge": (
        "[TASK=evidence_judge]\n"
        "Return the evidence-judge JSON schema only.\n"
        "Do not output prior-judge fields.\n\n"
    ),
    "prior_judge": (
        "[TASK=prior_judge]\n"
        "Return the prior-judge JSON schema only.\n"
        "Do not output evidence-judge fields.\n\n"
    ),
}


ALLOWED_ERROR_TYPES = {
    "correct_complete",
    "correct_weak_proof",
    "lucky_correct",
    "finalization_error",
    "valid_but_incomplete",
    "arithmetic_error",
    "algebraic_error",
    "invalid_assumption",
    "strategy_mismatch",
    "wrong_direction",
    "format_error",
    "no_meaningful_solution",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Offline posterior recomputation using a learned unified analyzer."
    )

    parser.add_argument("--input_debug_jsonl", required=True)
    parser.add_argument("--output_dir", required=True)

    parser.add_argument("--model_name", default="Qwen/Qwen2.5-3B-Instruct")
    parser.add_argument("--adapter_path", required=True)

    parser.add_argument("--max_groups", type=int, default=0)
    parser.add_argument("--batch_size", type=int, default=8)
    parser.add_argument("--max_new_tokens", type=int, default=512)
    parser.add_argument("--max_input_tokens", type=int, default=4096)
    parser.add_argument("--bf16", action="store_true")

    parser.add_argument("--answer_weight", type=float, default=0.8)
    parser.add_argument("--evidence_weight", type=float, default=0.2)
    parser.add_argument("--prior_lambda", type=float, default=1.0)
    parser.add_argument("--prior_temperature", type=float, default=1.0)

    parser.add_argument(
        "--fallback_mode",
        choices=["neutral", "teacher"],
        default="neutral",
        help=(
            "Fallback used when learned analyzer JSON parse/schema fails. "
            "neutral = suitability 2 / evidence scores 0. "
            "teacher = use teacher fields from debug log when available."
        ),
    )
    parser.add_argument(
        "--no_task_prefix",
        action="store_true",
        help="Disable [TASK=...] prefix. By default, prefix is used to match unified SFT data.",
    )

    return parser.parse_args()


def import_torch():
    try:
        import torch
    except ImportError as exc:
        raise RuntimeError("torch is required. Install it with `pip install torch`.") from exc
    return torch


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                row = json.loads(stripped)
            except json.JSONDecodeError as exc:
                raise RuntimeError(f"Invalid JSONL at {path}:{line_number}") from exc
            if not isinstance(row, dict):
                raise RuntimeError(f"Expected JSON object at {path}:{line_number}")
            rows.append(row)
    return rows


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False))
            handle.write("\n")


def load_tokenizer(model_name: str):
    from transformers import AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    tokenizer.padding_side = "left"
    tokenizer.truncation_side = "left"
    return tokenizer


def load_model(model_name: str, adapter_path: str, bf16: bool):
    torch = import_torch()
    from transformers import AutoModelForCausalLM
    from peft import PeftModel

    model_kwargs: dict[str, Any] = {
        "trust_remote_code": True,
        "torch_dtype": torch.bfloat16 if (bf16 and torch.cuda.is_available()) else "auto",
    }

    if torch.cuda.is_available():
        model_kwargs["device_map"] = {"": 0}

    base_model = AutoModelForCausalLM.from_pretrained(model_name, **model_kwargs)
    model = PeftModel.from_pretrained(base_model, adapter_path)
    model.eval()

    return model


def render_chat_prompt(messages: list[dict[str, str]], tokenizer: Any) -> str:
    try:
        return tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=False,
        )
    except TypeError:
        return tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )


def batch_generate(
    model: Any,
    tokenizer: Any,
    prompts: list[str],
    *,
    batch_size: int,
    max_new_tokens: int,
    max_input_tokens: int,
) -> list[str]:
    torch = import_torch()
    outputs: list[str] = []

    for start in range(0, len(prompts), batch_size):
        batch_prompts = prompts[start : start + batch_size]

        tokenized = tokenizer(
            batch_prompts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_input_tokens,
        )

        if torch.cuda.is_available():
            tokenized = {key: value.to(model.device) for key, value in tokenized.items()}

        with torch.no_grad():
            generated = model.generate(
                **tokenized,
                max_new_tokens=max_new_tokens,
                do_sample=False,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )

        input_width = tokenized["input_ids"].shape[1]
        for i in range(generated.shape[0]):
            new_tokens = generated[i][input_width:]
            decoded = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
            outputs.append(decoded)

        done = min(start + batch_size, len(prompts))
        print(f"[INFO] generated {done}/{len(prompts)} prompts")

    return outputs


def escape_invalid_json_backslashes(text: str) -> str:
    return re.sub(r'\\(?!["\\/bfnrtu])', r"\\\\", text)


def safe_json_parse(text: str) -> Optional[dict[str, Any]]:
    cleaned = str(text or "").strip()
    cleaned = cleaned.replace("```json", "").replace("```JSON", "").replace("```", "").strip()

    candidates = [cleaned]
    first_obj = cleaned.find("{")
    last_obj = cleaned.rfind("}")

    if first_obj != -1 and last_obj != -1 and last_obj > first_obj:
        candidates.append(cleaned[first_obj : last_obj + 1])

    expanded: list[str] = []
    for candidate in candidates:
        expanded.append(candidate)
        expanded.append(escape_invalid_json_backslashes(candidate))

    for candidate in expanded:
        try:
            parsed = json.loads(candidate)
        except json.JSONDecodeError:
            continue
        if isinstance(parsed, dict):
            return parsed

    return None


def format_required_rollout_ids(num_rollouts: int) -> str:
    return ", ".join(str(rollout_id) for rollout_id in range(num_rollouts))


# Exactly matched to prepare_analyzer_training_data.py prompt body.
def build_prior_judge_prompt(problem_text: str, rollouts: list[dict[str, Any]], num_rollouts: int) -> str:
    strategies_block = "\n\n".join(
        f"Rollout {rollout['rollout_id']}:\n{rollout['strategy'] or '(empty strategy)'}"
        for rollout in rollouts
    )
    required_rollout_ids = format_required_rollout_ids(num_rollouts)
    return f"""
You are a mathematical strategy evaluator.

You will be given a math problem and several candidate strategies generated by a solver.
Your task is to evaluate how promising each strategy is before seeing the actual solution.

Important rules:
- Do not solve the full problem.
- Do not look at reasoning or final answers.
- Evaluate only whether the strategy is appropriate for the problem type.
- Similar strategies may receive similar scores.
- The strategies do not need to be unique.
- Use suitability as an integer from 0 to 4.
- 0 = unsuitable or vague
- 1 = weak
- 2 = partially useful
- 3 = good
- 4 = very strong/directly appropriate
- Do not output prior_probability.
- The code will compute prior probabilities from suitability scores.
- Do not use LaTeX notation in any JSON string field.
- Do not use backslashes.
- Write reason and risk_flag in plain English only.
- You must evaluate every rollout_id from 0 to {num_rollouts - 1}.
- Return exactly {num_rollouts} items in the "priors" list.
- For num_rollouts = {num_rollouts}, return exactly rollout_id {required_rollout_ids}.
- Do not omit any rollout_id.
- Do not merge similar strategies.
- Even if two strategies are identical or very similar, evaluate both separately.
- If a strategy is weak, still include it with low suitability.
- Each rollout_id must appear exactly once.
- Do not invent rollout IDs.
- Do not return fewer than {num_rollouts} rows.
- Do not return more than {num_rollouts} rows.
- suitability must be an integer from 0 to 4.

Return only valid JSON.
The first character must be {{ and the last character must be }}.

JSON schema:
{{
  "priors": [
    {{
      "rollout_id": 0,
      "suitability": 3,
      "reason": "Uses the structure of the problem directly.",
      "risk_flag": "none"
    }}
  ]
}}

Problem:
{problem_text}

Candidate strategies:
{strategies_block}
""".strip()


# Exactly matched to prepare_analyzer_training_data.py prompt body.
def build_evidence_judge_prompt(
    problem_text: str,
    strategy: str,
    reasoning: str,
    final_answer: str,
    answer_correctness: float,
) -> str:
    return f"""
Return ONLY a valid JSON object.
Do not include markdown.
Do not include ```json.
Do not include explanations outside JSON.
The first character of your response must be {{ and the last character must be }}.

You are a strict mathematical reasoning judge.

You are given:
1. A math problem
2. The solver's stated strategy
3. The solver's reasoning trajectory
4. The solver's final answer
5. A deterministic correctness flag

The correctness flag is authoritative.
Do not override it.
Your task is not to solve the problem from scratch.
Your task is to evaluate the reliability of the reasoning trajectory.

Important rules:
- Do not reward verbosity.
- Do not reward a solution merely because it sounds fluent.
- Penalize hidden gaps, invalid assumptions, unsupported jumps, contradictions, and strategy mismatch.
- If the final answer is correct but the reasoning is flawed, classify it as lucky_correct or correct_weak_proof.
- If the final answer is incorrect but the reasoning is mostly valid, classify it as finalization_error or valid_but_incomplete.
- If the approach is fundamentally unsuitable, classify it as wrong_direction.
- Use the provided correctness flag as the final authority on answer correctness.

Error type consistency:
- If deterministic correctness flag is 0, error_type must NOT be correct_complete, correct_weak_proof, or lucky_correct.
- If deterministic correctness flag is 1, error_type should be one of correct_complete, correct_weak_proof, or lucky_correct unless there is a format issue.
- Treat the deterministic correctness flag as authoritative.

Evaluate the trajectory using the following rubric.

[Step Validity: 0-4]
0 = no meaningful valid reasoning
1 = major invalid step early in the solution
2 = some correct steps but a key mathematical error exists
3 = mostly valid with minor flaws
4 = all major steps are mathematically valid

[Proof Completeness: 0-4]
0 = no proof or only final answer
1 = central derivation is missing
2 = key idea exists but important steps are omitted
3 = almost complete with minor omissions
4 = complete and self-contained

[Strategy Compliance: 0-4]
0 = does not follow the stated strategy
1 = mentions the strategy but mostly deviates
2 = partially follows the strategy
3 = mostly follows the strategy
4 = the strategy is central to the solution

[Consistency: 0-4]
0 = severe contradictions in variables, assumptions, or final answer
1 = frequent inconsistencies
2 = some inconsistencies but partially traceable
3 = mostly consistent
4 = fully internally consistent

[Error Type]
Choose exactly one:
correct_complete,
correct_weak_proof,
lucky_correct,
finalization_error,
valid_but_incomplete,
arithmetic_error,
algebraic_error,
invalid_assumption,
strategy_mismatch,
wrong_direction,
format_error,
no_meaningful_solution

Return JSON only.

JSON schema:
{{
  "step_validity": 0,
  "proof_completeness": 0,
  "strategy_compliance": 0,
  "consistency": 0,
  "error_type": "",
  "key_strength": "",
  "key_weakness": "",
  "critical_failure_step": "",
  "judge_confidence": 0.0
}}

Problem:
{problem_text}

Strategy:
{strategy or "(empty strategy)"}

Reasoning:
{reasoning or "(empty reasoning)"}

Final Answer:
{final_answer or "(empty final answer)"}

Deterministic correctness flag:
{int(answer_correctness)}

Final output rules:
- Return ONLY one valid JSON object.
- Do not include markdown.
- Do not include a code block.
- Do not include any explanation outside the JSON.
- Do not use LaTeX notation in any JSON string value.
- Do not use backslashes.
- Write mathematical expressions in plain English text.
- Use exactly the keys shown in the JSON schema.
- The response must start with {{ and end with }}.
""".strip()


def maybe_add_task_prefix(prompt: str, task: str, use_task_prefix: bool) -> str:
    if not use_task_prefix:
        return prompt
    return TASK_PREFIXES[task] + prompt


def build_messages(prompt: str) -> list[dict[str, str]]:
    return [
        {"role": "system", "content": JUDGE_JSON_SYSTEM_PROMPT},
        {"role": "user", "content": prompt},
    ]


def get_group_key(row: dict[str, Any]) -> tuple[Any, Any]:
    return (
        row.get("global_reward_call_index"),
        row.get("group_index_within_call"),
    )


def get_rollout_id(row: dict[str, Any]) -> int:
    return int(row.get("group_rollout_id", row.get("rollout_id", 0)))


def group_rows(rows: list[dict[str, Any]]) -> list[list[dict[str, Any]]]:
    grouped: dict[tuple[Any, Any], list[dict[str, Any]]] = defaultdict(list)

    for row in rows:
        grouped[get_group_key(row)].append(row)

    groups = []
    for _, group in sorted(grouped.items(), key=lambda item: str(item[0])):
        groups.append(sorted(group, key=get_rollout_id))

    return groups


def softmax(values: list[float], temperature: float) -> list[float]:
    if not values:
        return []

    temperature = max(float(temperature), 1e-8)
    scaled = [value / temperature for value in values]
    max_value = max(scaled)
    exps = [math.exp(value - max_value) for value in scaled]
    total = sum(exps)

    if total <= 0:
        return [1.0 / len(values)] * len(values)

    return [value / total for value in exps]


def normalized_entropy(probs: list[float]) -> float:
    if not probs:
        return 0.0
    if len(probs) == 1:
        return 0.0

    entropy = 0.0
    for prob in probs:
        if prob > 0:
            entropy -= prob * math.log(prob)

    return entropy / math.log(len(probs))


def top1_top2_gap(values: list[float]) -> float:
    if len(values) < 2:
        return 0.0
    sorted_values = sorted(values, reverse=True)
    return sorted_values[0] - sorted_values[1]


def validate_prior_json(
    parsed: Optional[dict[str, Any]],
    num_rollouts: int,
) -> tuple[bool, dict[int, int], dict[str, Any]]:
    if not isinstance(parsed, dict):
        return False, {}, {"parse_failed": True}

    priors = parsed.get("priors")
    if not isinstance(priors, list):
        return False, {}, {"priors_not_list": True}

    suitability_by_id: dict[int, int] = {}
    duplicate_ids: list[int] = []
    invalid_rows = 0

    for item in priors:
        if not isinstance(item, dict):
            invalid_rows += 1
            continue
        try:
            rollout_id = int(item.get("rollout_id"))
            suitability = int(item.get("suitability"))
        except (TypeError, ValueError):
            invalid_rows += 1
            continue

        if suitability < 0 or suitability > 4:
            invalid_rows += 1
            continue

        if rollout_id in suitability_by_id:
            duplicate_ids.append(rollout_id)

        suitability_by_id[rollout_id] = suitability

    missing_ids = [
        rollout_id
        for rollout_id in range(num_rollouts)
        if rollout_id not in suitability_by_id
    ]

    ok = (
        not missing_ids
        and not duplicate_ids
        and invalid_rows == 0
        and len(priors) == num_rollouts
    )

    debug = {
        "missing_ids": missing_ids,
        "duplicate_ids": duplicate_ids,
        "invalid_rows": invalid_rows,
        "rows_returned": len(priors),
    }

    return ok, suitability_by_id, debug


def validate_evidence_json(
    parsed: Optional[dict[str, Any]],
) -> tuple[bool, dict[str, Any], dict[str, Any]]:
    required = [
        "step_validity",
        "proof_completeness",
        "strategy_compliance",
        "consistency",
        "error_type",
        "key_strength",
        "key_weakness",
        "critical_failure_step",
        "judge_confidence",
    ]

    if not isinstance(parsed, dict):
        return False, {}, {"parse_failed": True}

    missing = [key for key in required if key not in parsed]
    if missing:
        return False, {}, {"missing_keys": missing}

    try:
        scores = {
            "step_validity": int(parsed["step_validity"]),
            "proof_completeness": int(parsed["proof_completeness"]),
            "strategy_compliance": int(parsed["strategy_compliance"]),
            "consistency": int(parsed["consistency"]),
        }
        judge_confidence = float(parsed["judge_confidence"])
    except (TypeError, ValueError):
        return False, {}, {"invalid_numeric_field": True}

    if any(value < 0 or value > 4 for value in scores.values()):
        return False, {}, {"score_out_of_range": scores}

    error_type = str(parsed.get("error_type", ""))
    if error_type not in ALLOWED_ERROR_TYPES:
        return False, {}, {"invalid_error_type": error_type}

    result = {
        **scores,
        "error_type": error_type,
        "key_strength": str(parsed.get("key_strength", "") or ""),
        "key_weakness": str(parsed.get("key_weakness", "") or ""),
        "critical_failure_step": str(parsed.get("critical_failure_step", "") or ""),
        "judge_confidence": judge_confidence,
    }

    return True, result, {}


def fallback_prior_suitability(row: dict[str, Any], fallback_mode: str) -> int:
    if fallback_mode == "teacher" and "prior_suitability" in row:
        try:
            return int(row["prior_suitability"])
        except Exception:
            pass
    return 2


def fallback_evidence_scores(row: dict[str, Any], fallback_mode: str) -> dict[str, Any]:
    if fallback_mode == "teacher":
        needed = ["step_validity", "proof_completeness", "strategy_compliance", "consistency"]
        if all(key in row for key in needed):
            try:
                return {
                    "step_validity": int(row["step_validity"]),
                    "proof_completeness": int(row["proof_completeness"]),
                    "strategy_compliance": int(row["strategy_compliance"]),
                    "consistency": int(row["consistency"]),
                    "error_type": str(row.get("error_type", "format_error") or "format_error"),
                    "key_strength": str(row.get("key_strength", "") or ""),
                    "key_weakness": str(row.get("key_weakness", "") or ""),
                    "critical_failure_step": str(row.get("critical_failure_step", "") or ""),
                    "judge_confidence": float(row.get("judge_confidence", 0.0)),
                }
            except Exception:
                pass

    return {
        "step_validity": 0,
        "proof_completeness": 0,
        "strategy_compliance": 0,
        "consistency": 0,
        "error_type": "format_error",
        "key_strength": "",
        "key_weakness": "Learned analyzer output failed to parse or validate.",
        "critical_failure_step": "",
        "judge_confidence": 0.0,
    }


def compute_likelihood(
    evidence_scores: dict[str, Any],
    answer_correctness: float,
    answer_weight: float,
    evidence_weight: float,
) -> tuple[float, float]:
    score_fields = [
        "step_validity",
        "proof_completeness",
        "strategy_compliance",
        "consistency",
    ]

    evidence_quality = statistics.fmean(
        float(evidence_scores[field]) for field in score_fields
    ) / 4.0

    likelihood = answer_weight * float(answer_correctness) + evidence_weight * evidence_quality
    likelihood = max(0.0, min(1.0, likelihood))

    return likelihood, evidence_quality


def main() -> None:
    args = parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = load_jsonl(Path(args.input_debug_jsonl))
    groups = group_rows(rows)

    if args.max_groups and args.max_groups > 0:
        groups = groups[: args.max_groups]

    print(f"[INFO] loaded rows={len(rows)} groups={len(groups)}")
    print(f"[INFO] output_dir={output_dir}")
    print(f"[INFO] task_prefix_enabled={not args.no_task_prefix}")

    tokenizer = load_tokenizer(args.model_name)
    model = load_model(args.model_name, args.adapter_path, args.bf16)

    use_task_prefix = not args.no_task_prefix

    # -------------------------
    # 1. Prior prompts
    # -------------------------
    prior_prompt_records: list[dict[str, Any]] = []
    prior_prompts: list[str] = []

    for group_index, group in enumerate(groups):
        problem = str(group[0].get("problem", "") or "")
        rollouts = [
            {
                "rollout_id": get_rollout_id(row),
                "strategy": str(row.get("parsed_strategy", "") or ""),
            }
            for row in group
        ]

        prompt = build_prior_judge_prompt(problem, rollouts, len(group))
        prompt = maybe_add_task_prefix(prompt, "prior_judge", use_task_prefix)

        messages = build_messages(prompt)
        rendered = render_chat_prompt(messages, tokenizer)

        prior_prompt_records.append(
            {
                "group_index": group_index,
                "group_key": list(get_group_key(group[0])),
                "num_rollouts": len(group),
            }
        )
        prior_prompts.append(rendered)

    print(f"[INFO] running prior_judge prompts={len(prior_prompts)}")
    prior_raw_outputs = batch_generate(
        model,
        tokenizer,
        prior_prompts,
        batch_size=args.batch_size,
        max_new_tokens=args.max_new_tokens,
        max_input_tokens=args.max_input_tokens,
    )

    learned_prior_by_group: dict[int, dict[int, int]] = {}
    prior_parse_ok_by_group: dict[int, bool] = {}
    prior_debug_by_group: dict[int, dict[str, Any]] = {}

    for record, raw_output in zip(prior_prompt_records, prior_raw_outputs):
        group_index = int(record["group_index"])
        num_rollouts = int(record["num_rollouts"])

        parsed = safe_json_parse(raw_output)
        ok, suitability_by_id, debug = validate_prior_json(parsed, num_rollouts)

        if not ok:
            suitability_by_id = {}

        learned_prior_by_group[group_index] = suitability_by_id
        prior_parse_ok_by_group[group_index] = ok
        prior_debug_by_group[group_index] = {
            "ok": ok,
            "debug": debug,
            "raw_output": raw_output,
            "parsed_json": parsed,
        }

    # -------------------------
    # 2. Evidence prompts
    # -------------------------
    evidence_prompt_records: list[dict[str, Any]] = []
    evidence_prompts: list[str] = []

    for group_index, group in enumerate(groups):
        for row in group:
            problem = str(row.get("problem", "") or "")
            strategy = str(row.get("parsed_strategy", "") or "")
            reasoning = str(row.get("parsed_reasoning", "") or "")
            final_answer = str(row.get("parsed_final_answer", "") or "")
            answer_correctness = float(row.get("answer_correctness", 0.0))

            prompt = build_evidence_judge_prompt(
                problem,
                strategy,
                reasoning,
                final_answer,
                answer_correctness,
            )
            prompt = maybe_add_task_prefix(prompt, "evidence_judge", use_task_prefix)

            messages = build_messages(prompt)
            rendered = render_chat_prompt(messages, tokenizer)

            evidence_prompt_records.append(
                {
                    "group_index": group_index,
                    "rollout_id": get_rollout_id(row),
                }
            )
            evidence_prompts.append(rendered)

    print(f"[INFO] running evidence_judge prompts={len(evidence_prompts)}")
    evidence_raw_outputs = batch_generate(
        model,
        tokenizer,
        evidence_prompts,
        batch_size=args.batch_size,
        max_new_tokens=args.max_new_tokens,
        max_input_tokens=args.max_input_tokens,
    )

    learned_evidence_by_key: dict[tuple[int, int], dict[str, Any]] = {}
    evidence_parse_ok_by_key: dict[tuple[int, int], bool] = {}
    evidence_debug_by_key: dict[tuple[int, int], dict[str, Any]] = {}

    for record, raw_output in zip(evidence_prompt_records, evidence_raw_outputs):
        group_index = int(record["group_index"])
        rollout_id = int(record["rollout_id"])
        key = (group_index, rollout_id)

        parsed = safe_json_parse(raw_output)
        ok, evidence_scores, debug = validate_evidence_json(parsed)

        learned_evidence_by_key[key] = evidence_scores if ok else {}
        evidence_parse_ok_by_key[key] = ok
        evidence_debug_by_key[key] = {
            "ok": ok,
            "debug": debug,
            "raw_output": raw_output,
            "parsed_json": parsed,
        }

    # -------------------------
    # 3. Recompute posterior
    # -------------------------
    output_rows: list[dict[str, Any]] = []
    group_metric_rows: list[dict[str, Any]] = []

    prior_parse_success = 0
    evidence_parse_success = 0
    total_evidence = 0

    for group_index, group in enumerate(groups):
        num_rollouts = len(group)

        if prior_parse_ok_by_group.get(group_index, False):
            prior_parse_success += 1

        learned_suitabilities: list[int] = []
        for row in group:
            rid = get_rollout_id(row)
            suitability_by_id = learned_prior_by_group.get(group_index, {})
            if rid in suitability_by_id:
                learned_suitabilities.append(int(suitability_by_id[rid]))
            else:
                learned_suitabilities.append(
                    fallback_prior_suitability(row, args.fallback_mode)
                )

        learned_prior_probs = softmax(learned_suitabilities, args.prior_temperature)

        learned_likelihoods: list[float] = []
        learned_evidence_qualities: list[float] = []
        learned_evidence_scores_list: list[dict[str, Any]] = []

        for row in group:
            total_evidence += 1
            rid = get_rollout_id(row)
            key = (group_index, rid)

            if evidence_parse_ok_by_key.get(key, False):
                evidence_parse_success += 1
                evidence_scores = learned_evidence_by_key[key]
            else:
                evidence_scores = fallback_evidence_scores(row, args.fallback_mode)

            likelihood, evidence_quality = compute_likelihood(
                evidence_scores=evidence_scores,
                answer_correctness=float(row.get("answer_correctness", 0.0)),
                answer_weight=args.answer_weight,
                evidence_weight=args.evidence_weight,
            )

            learned_likelihoods.append(likelihood)
            learned_evidence_qualities.append(evidence_quality)
            learned_evidence_scores_list.append(evidence_scores)

        learned_scores = [
            (prior_prob ** args.prior_lambda) * likelihood
            for prior_prob, likelihood in zip(learned_prior_probs, learned_likelihoods)
        ]

        score_sum = sum(learned_scores)
        if score_sum <= 0:
            learned_posteriors = [1.0 / num_rollouts] * num_rollouts
            posterior_fallback = True
        else:
            learned_posteriors = [score / score_sum for score in learned_scores]
            posterior_fallback = False

        teacher_posteriors = [float(row.get("bayesian_reward", 0.0)) for row in group]
        answer_correctness_values = [float(row.get("answer_correctness", 0.0)) for row in group]

        learned_top_idx = max(range(num_rollouts), key=lambda idx: learned_posteriors[idx])
        teacher_top_idx = max(range(num_rollouts), key=lambda idx: teacher_posteriors[idx])

        learned_top_correct = answer_correctness_values[learned_top_idx] == 1.0
        teacher_top_correct = answer_correctness_values[teacher_top_idx] == 1.0

        any_correct = any(value == 1.0 for value in answer_correctness_values)

        learned_mass_on_correct = sum(
            posterior
            for posterior, correct in zip(learned_posteriors, answer_correctness_values)
            if correct == 1.0
        )

        teacher_mass_on_correct = sum(
            posterior
            for posterior, correct in zip(teacher_posteriors, answer_correctness_values)
            if correct == 1.0
        )

        learned_wrong_top = any_correct and not learned_top_correct
        teacher_wrong_top = any_correct and not teacher_top_correct

        group_metric_rows.append(
            {
                "group_index": group_index,
                "group_key": list(get_group_key(group[0])),
                "num_rollouts": num_rollouts,
                "any_correct": any_correct,
                "teacher_top_correct": teacher_top_correct,
                "learned_top_correct": learned_top_correct,
                "teacher_wrong_top": teacher_wrong_top,
                "learned_wrong_top": learned_wrong_top,
                "teacher_mass_on_correct": teacher_mass_on_correct,
                "learned_mass_on_correct": learned_mass_on_correct,
                "teacher_entropy": normalized_entropy(teacher_posteriors),
                "learned_entropy": normalized_entropy(learned_posteriors),
                "teacher_top1_top2_gap": top1_top2_gap(teacher_posteriors),
                "learned_top1_top2_gap": top1_top2_gap(learned_posteriors),
                "posterior_fallback": posterior_fallback,
                "prior_parse_ok": prior_parse_ok_by_group.get(group_index, False),
            }
        )

        for local_idx, row in enumerate(group):
            rid = get_rollout_id(row)
            key = (group_index, rid)

            output_row = {
                "group_index": group_index,
                "group_key": list(get_group_key(row)),
                "rollout_id": rid,
                "problem": row.get("problem", ""),
                "answer_correctness": float(row.get("answer_correctness", 0.0)),

                "teacher_prior_suitability": row.get("prior_suitability"),
                "teacher_prior_probability": row.get("prior_probability"),
                "teacher_likelihood": row.get("likelihood"),
                "teacher_posterior": float(row.get("bayesian_reward", 0.0)),

                "learned_prior_suitability": learned_suitabilities[local_idx],
                "learned_prior_probability": learned_prior_probs[local_idx],
                "learned_evidence_scores": learned_evidence_scores_list[local_idx],
                "learned_evidence_quality": learned_evidence_qualities[local_idx],
                "learned_likelihood": learned_likelihoods[local_idx],
                "learned_unnormalized_score": learned_scores[local_idx],
                "learned_posterior": learned_posteriors[local_idx],

                "prior_parse_ok": prior_parse_ok_by_group.get(group_index, False),
                "evidence_parse_ok": evidence_parse_ok_by_key.get(key, False),
                "posterior_fallback": posterior_fallback,

                "parsed_strategy": row.get("parsed_strategy", ""),
                "parsed_final_answer": row.get("parsed_final_answer", ""),
            }

            output_rows.append(output_row)

    write_jsonl(output_dir / "learned_posterior_debug.jsonl", output_rows)
    write_jsonl(output_dir / "group_metrics.jsonl", group_metric_rows)

    total_groups = len(group_metric_rows)
    groups_with_correct = [row for row in group_metric_rows if row["any_correct"]]

    teacher_top1_accuracy = statistics.fmean(
        1.0 if row["teacher_top_correct"] else 0.0 for row in group_metric_rows
    ) if group_metric_rows else 0.0

    learned_top1_accuracy = statistics.fmean(
        1.0 if row["learned_top_correct"] else 0.0 for row in group_metric_rows
    ) if group_metric_rows else 0.0

    teacher_top1_accuracy_when_correct_exists = statistics.fmean(
        1.0 if row["teacher_top_correct"] else 0.0 for row in groups_with_correct
    ) if groups_with_correct else 0.0

    learned_top1_accuracy_when_correct_exists = statistics.fmean(
        1.0 if row["learned_top_correct"] else 0.0 for row in groups_with_correct
    ) if groups_with_correct else 0.0

    teacher_wrong_top_count = sum(1 for row in group_metric_rows if row["teacher_wrong_top"])
    learned_wrong_top_count = sum(1 for row in group_metric_rows if row["learned_wrong_top"])

    summary = {
        "config": {
            "input_debug_jsonl": args.input_debug_jsonl,
            "model_name": args.model_name,
            "adapter_path": args.adapter_path,
            "max_groups": args.max_groups,
            "batch_size": args.batch_size,
            "max_new_tokens": args.max_new_tokens,
            "max_input_tokens": args.max_input_tokens,
            "answer_weight": args.answer_weight,
            "evidence_weight": args.evidence_weight,
            "prior_lambda": args.prior_lambda,
            "prior_temperature": args.prior_temperature,
            "fallback_mode": args.fallback_mode,
            "bf16": args.bf16,
            "task_prefix_enabled": use_task_prefix,
        },
        "counts": {
            "input_rows": len(rows),
            "groups_evaluated": total_groups,
            "groups_with_any_correct": len(groups_with_correct),
            "prior_parse_success": prior_parse_success,
            "prior_parse_rate": prior_parse_success / total_groups if total_groups else 0.0,
            "evidence_parse_success": evidence_parse_success,
            "total_evidence_judgments": total_evidence,
            "evidence_parse_rate": evidence_parse_success / total_evidence if total_evidence else 0.0,
            "posterior_fallback_count": sum(1 for row in group_metric_rows if row["posterior_fallback"]),
        },
        "teacher": {
            "posterior_top1_accuracy_all_groups": teacher_top1_accuracy,
            "posterior_top1_accuracy_when_correct_exists": teacher_top1_accuracy_when_correct_exists,
            "wrong_top_count_when_correct_exists": teacher_wrong_top_count,
            "mass_on_correct_mean": statistics.fmean(
                row["teacher_mass_on_correct"] for row in group_metric_rows
            ) if group_metric_rows else 0.0,
            "entropy_mean": statistics.fmean(
                row["teacher_entropy"] for row in group_metric_rows
            ) if group_metric_rows else 0.0,
            "top1_top2_gap_mean": statistics.fmean(
                row["teacher_top1_top2_gap"] for row in group_metric_rows
            ) if group_metric_rows else 0.0,
        },
        "learned": {
            "posterior_top1_accuracy_all_groups": learned_top1_accuracy,
            "posterior_top1_accuracy_when_correct_exists": learned_top1_accuracy_when_correct_exists,
            "wrong_top_count_when_correct_exists": learned_wrong_top_count,
            "mass_on_correct_mean": statistics.fmean(
                row["learned_mass_on_correct"] for row in group_metric_rows
            ) if group_metric_rows else 0.0,
            "entropy_mean": statistics.fmean(
                row["learned_entropy"] for row in group_metric_rows
            ) if group_metric_rows else 0.0,
            "top1_top2_gap_mean": statistics.fmean(
                row["learned_top1_top2_gap"] for row in group_metric_rows
            ) if group_metric_rows else 0.0,
        },
        "delta_learned_minus_teacher": {
            "posterior_top1_accuracy_all_groups": learned_top1_accuracy - teacher_top1_accuracy,
            "posterior_top1_accuracy_when_correct_exists": (
                learned_top1_accuracy_when_correct_exists
                - teacher_top1_accuracy_when_correct_exists
            ),
            "wrong_top_count_when_correct_exists": learned_wrong_top_count - teacher_wrong_top_count,
        },
        "diagnostics": {
            "prior_parse_rate": prior_parse_success / total_groups if total_groups else 0.0,
            "evidence_parse_rate": evidence_parse_success / total_evidence if total_evidence else 0.0,
            "fallback_count": sum(1 for row in group_metric_rows if row["posterior_fallback"]),
            "mass_on_correct": statistics.fmean(
                row["learned_mass_on_correct"] for row in group_metric_rows
            ) if group_metric_rows else 0.0,
            "posterior_top1_accuracy": learned_top1_accuracy,
            "entropy": statistics.fmean(
                row["learned_entropy"] for row in group_metric_rows
            ) if group_metric_rows else 0.0,
            "top1_top2_gap": statistics.fmean(
                row["learned_top1_top2_gap"] for row in group_metric_rows
            ) if group_metric_rows else 0.0,
            "wrong_high_posterior_count": learned_wrong_top_count,
        },
    }

    write_json(output_dir / "summary.json", summary)

    print(f"[INFO] wrote outputs to {output_dir}")
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
